weightOnEarth = float(input("Enter Your Weight on Earth : "))
weightOnMoon = round((weightOnEarth*1.622)/9.81)
weightOnMercury = round((weightOnEarth/9.81)*3.7)
weightOnMars = round((weightOnEarth/9.81)*3.711)
weightOnUranus = round((weightOnEarth/9.81)*8.69)
weightOnVenus = round((weightOnEarth/9.81)*8.87)
weightOnSaturn = round((weightOnEarth/9.81)*10.44)
weightOnNeptune = round((weightOnEarth/9.81)*11.15)
weightOnJupiter = round((weightOnEarth/9.81)*24.79)
print("Your weight on Moon is : "+str(weightOnMoon))
print("Your weight on Mercury is : "+str(weightOnMercury))
print("Your weight on Mars is : "+str(weightOnMars))
print("Your weight on Venus is : "+str(weightOnVenus))
print("Your weight on Saturn is : "+str(weightOnSaturn))
print("Your weight on Neptune is : "+str(weightOnNeptune))
print("Your weight on Jupiter is : "+str(weightOnJupiter))

